// book/examples/counter/vue/Counter.vue
<script setup lang="ts">
import { useHail, useReadHail, useTell } from "../../setup/vue/bridge";

const count = useHail("Count"); // writable ref
const doubled = useReadHail("Doubled"); // read-only memo
const tell = useTell();
</script>

<template>
  <div class="demo">
    <p>
      count: <b id="count">{{ count }}</b> · doubled: <b id="doubled">{{ doubled }}</b>
    </p>
    <button id="write-count" @click="count++">+1 (write)</button>
    <button id="tell-increase" @click="tell('Increase')">+1 (tell)</button>
  </div>
</template>

// book/examples/counter/react/Counter.tsx
import { useHail, useReadHail, useTell } from "../../setup/react/bridge";

export default function Counter() {
    const [count, setCount] = useHail("Count"); // writable
    const doubled = useReadHail("Doubled"); // read-only memo
    const tell = useTell();

    return (
        <div className="demo">
            <p>
                count: <b id="count">{count}</b> · doubled: <b id="doubled">{doubled}</b>
            </p>
            <button id="write-count" onClick={() => setCount(count + 1)}>
                +1 (write)
            </button>
            <button id="tell-increase" onClick={() => tell("Increase")}>
                +1 (tell)
            </button>
        </div>
    );
}
