// playgrounds/svelte/src/App.svelte
<script lang="ts">
    /**
     * Each section exercises one bridge feature — see the table in
     * `playgrounds/ahoi-wasm-tsrs/src/lib.rs`. Mirrors the other playgrounds
     * (same element ids).
     *
     * Svelte has no provider component here: `providePier` sets the pier for
     * this component and everything below it.
     */
    import { providePier } from "./bridge";
    import Counter from "./Counter.svelte";
    import Items from "./Items.svelte";
    import Fruits from "./Fruits.svelte";
    import Panel from "./Panel.svelte";
    import PanicDemo from "./PanicDemo.svelte";

    providePier("Top");
    let showPanel = $state(false);
</script>

<h1>ahoi × svelte</h1>
<Counter />
<Items />
<Fruits />
<section>
    <button id="toggle-panel" onclick={() => (showPanel = !showPanel)}>
        {showPanel ? "unmount panel" : "mount panel"}
    </button>
    {#if showPanel}
        <Panel />
    {/if}
</section>
<PanicDemo />

// playgrounds/vue/src/App.vue
<script setup lang="ts">
/**
 * Each section exercises one bridge feature — see the table in
 * `playgrounds/ahoi-wasm-tsrs/src/lib.rs`. Mirrors the solid/react playgrounds
 * (same element ids).
 */
import { ref } from "vue";
import { PierProvider } from "./bridge";
import Counter from "./Counter.vue";
import Items from "./Items.vue";
import Fruits from "./Fruits.vue";
import Panel from "./Panel.vue";
import PanicDemo from "./PanicDemo.vue";

const showPanel = ref(false);
</script>

<template>
  <PierProvider pier="Top">
    <h1>ahoi × vue</h1>
    <Counter />
    <Items />
    <Fruits />
    <section>
      <button id="toggle-panel" @click="showPanel = !showPanel">
        {{ showPanel ? "unmount panel" : "mount panel" }}
      </button>
      <PierProvider v-if="showPanel" pier="Panel">
        <Panel />
      </PierProvider>
    </section>
    <PanicDemo />
  </PierProvider>
</template>
